/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...404]': RouteRecordInfo<'/[...404]', '/:404(.*)', { 404: ParamValue<true> }, { 404: ParamValue<false> }>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/collective-sponsor-onetime': RouteRecordInfo<'/collective-sponsor-onetime', '/collective-sponsor-onetime', Record<never, never>, Record<never, never>>,
    '/demos': RouteRecordInfo<'/demos', '/demos', Record<never, never>, Record<never, never>>,
    '/demos/': RouteRecordInfo<'/demos/', '/demos', Record<never, never>, Record<never, never>>,
    '/demos/2024-02-02': RouteRecordInfo<'/demos/2024-02-02', '/demos/2024-02-02', Record<never, never>, Record<never, never>>,
    '/docs': RouteRecordInfo<'/docs', '/docs', Record<never, never>, Record<never, never>>,
    '/features': RouteRecordInfo<'/features', '/features', Record<never, never>, Record<never, never>>,
    '/notes': RouteRecordInfo<'/notes', '/notes', Record<never, never>, Record<never, never>>,
    '/notes/': RouteRecordInfo<'/notes/', '/notes', Record<never, never>, Record<never, never>>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/admonitions': RouteRecordInfo<'/posts/admonitions', '/posts/admonitions', Record<never, never>, Record<never, never>>,
    '/posts/art-styles': RouteRecordInfo<'/posts/art-styles', '/posts/art-styles', Record<never, never>, Record<never, never>>,
    '/posts/frontmatter-options': RouteRecordInfo<'/posts/frontmatter-options', '/posts/frontmatter-options', Record<never, never>, Record<never, never>>,
    '/posts/install': RouteRecordInfo<'/posts/install', '/posts/install', Record<never, never>, Record<never, never>>,
    '/posts/layout-options': RouteRecordInfo<'/posts/layout-options', '/posts/layout-options', Record<never, never>, Record<never, never>>,
    '/posts/markdown-features': RouteRecordInfo<'/posts/markdown-features', '/posts/markdown-features', Record<never, never>, Record<never, never>>,
    '/posts/navigation': RouteRecordInfo<'/posts/navigation', '/posts/navigation', Record<never, never>, Record<never, never>>,
    '/posts/page-types': RouteRecordInfo<'/posts/page-types', '/posts/page-types', Record<never, never>, Record<never, never>>,
    '/posts/site-structure': RouteRecordInfo<'/posts/site-structure', '/posts/site-structure', Record<never, never>, Record<never, never>>,
    '/posts/theme-config': RouteRecordInfo<'/posts/theme-config', '/posts/theme-config', Record<never, never>, Record<never, never>>,
    '/talks': RouteRecordInfo<'/talks', '/talks', Record<never, never>, Record<never, never>>,
  }
}
